import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from "react";
const findings = [
    { id: 'SEC-001', severity: 'High', title: 'Missing Authorization Check' },
    { id: 'SEC-002', severity: 'Medium', title: 'Sensitive Data in Logs' },
    { id: 'SEC-003', severity: 'Low', title: 'Security Headers Review' }
];
export default function SecurityReviewCenter() {
    const [selected, setSelected] = useState(findings[0]);
    return (_jsxs("div", { style: { padding: 24 }, children: [_jsx("h2", { children: "Security Review Center" }), _jsxs("div", { style: { display: 'grid', gridTemplateColumns: 'repeat(4,1fr)', gap: 12 }, children: [_jsx("div", { style: { padding: 12, border: '1px solid #ddd', borderRadius: 10 }, children: "Critical: 0" }), _jsx("div", { style: { padding: 12, border: '1px solid #ddd', borderRadius: 10 }, children: "High: 1" }), _jsx("div", { style: { padding: 12, border: '1px solid #ddd', borderRadius: 10 }, children: "Medium: 1" }), _jsx("div", { style: { padding: 12, border: '1px solid #ddd', borderRadius: 10 }, children: "Low: 1" })] }), _jsx("h3", { style: { marginTop: 20 }, children: "OWASP Review Checklist" }), _jsxs("ul", { children: [_jsx("li", { children: "Authentication Review" }), _jsx("li", { children: "Authorization Review" }), _jsx("li", { children: "Input Validation" }), _jsx("li", { children: "Secrets Management" }), _jsx("li", { children: "Dependency Scanning" }), _jsx("li", { children: "Logging & Audit Review" })] }), _jsxs("div", { style: { display: 'grid', gridTemplateColumns: '300px 1fr', gap: 16 }, children: [_jsx("div", { children: findings.map(f => (_jsxs("div", { onClick: () => setSelected(f), style: { cursor: 'pointer', border: '1px solid #ddd', padding: 12, marginBottom: 8, borderRadius: 10 }, children: [f.id, " - ", f.title] }, f.id))) }), _jsxs("div", { style: { border: '1px solid #ddd', padding: 16, borderRadius: 10 }, children: [_jsx("h4", { children: selected.id }), _jsx("p", { children: selected.title }), _jsxs("p", { children: ["Severity: ", selected.severity] }), _jsx("h4", { children: "Mitigation" }), _jsx("p", { children: "Document remediation steps, validation evidence, and verification status." })] })] }), _jsx("h3", { children: "Security Approval Workflow" }), _jsx("pre", { children: "Assessment -> Findings -> Remediation -> Verification -> Approval" })] }));
}
